### ISSUE TITLE
Ошибка при скачивании файла TimeoutError: waiting for selector `div[data-testid="dropdown-option-File"]`

### ISSUE THREAD

**Issue by austyuzhaninov** [ritds/figma_backup#12]
Добрый день, при выполнении команды:  ./manage.sh <логин> <пароль> падает в ошибку:

 Python 2.7.18
 node v16.13.0

settings:  {
  downloadTimeout: 300,
  selectorTimeout: 20000,
  navigationTimeout: 180000,
  launchTimeout: 120000,
  loginTimeout: 10000,
  pageOpenTimeout: 10000
}

Opening the login page
Filling the email field
Filling the password field
Clicking the submit button
Waiting for an after-login page opening
Tmp directory to save the file: ./process/_downloads/tmp/

...

Starting to process new file (3/3), url: https://www.figma.com/file/*******************
Opening the file page: https://www.figma.com/file/*******************
Returned status: 200
Directory to save the file: ./process/_downloads/TEAM/PROJECT foo/
cannot open main menu
TimeoutError: waiting for selector `div[data-testid="dropdown-option-File"]` failed: timeout 20000ms exceeded
    at new WaitTask (/home/arseniy/soft/figma_backup-master/node_modules/puppeteer/lib/cjs/puppeteer/common/DOMWorld.js:528:34)
    at DOMWorld.waitForSelectorInPage (/home/arseniy/soft/figma_backup-master/node_modules/puppeteer/lib/cjs/puppeteer/common/DOMWorld.js:432:26)
    at Object.internalHandler.waitFor (/home/arseniy/soft/figma_backup-master/node_modules/puppeteer/lib/cjs/puppeteer/common/QueryHandler.js:31:77)
    at DOMWorld.waitForSelector (/home/arseniy/soft/figma_backup-master/node_modules/puppeteer/lib/cjs/puppeteer/common/DOMWorld.js:323:29)
    at Frame.waitForSelector (/home/arseniy/soft/figma_backup-master/node_modules/puppeteer/lib/cjs/puppeteer/common/FrameManager.js:936:51)
    at Page.waitForSelector (/home/arseniy/soft/figma_backup-master/node_modules/puppeteer/lib/cjs/puppeteer/common/Page.js:2359:33)
    at /home/arseniy/soft/figma_backup-master/download_figma_files.js:278:49
DONE

Пробовал увеличить timeout не помогает

**Comment by paulmixxx** [comment]
Проверь логин и пароль.
