### ISSUE TITLE
Ошибка при скачивании файла Cannot read properties of null (reading 'dispatchEvent')

### ISSUE THREAD

**Issue by YarMag** [ritds/figma_backup#15]
Сегодня скрипт перестал скачивать файлы из фигмы. Доступы есть, токены валидные, смена пользователя результата не дала, в дебаг-папке актуальные скрины и валидный html. Однако любой файл валится с ошибкой вот такого вида:

Starting to process new file (1/493), url: https://www.figma.com/file/file_uuid/
Opening the file page: https://www.figma.com/file/file_uuid/
Returned status: 200
Directory to save the file: ./process/_downloads/MyProject/
Error: Evaluation failed: TypeError: Cannot read properties of null (reading 'dispatchEvent')
    at __puppeteer_evaluation_script__:5:26
    at ExecutionContext._evaluateInternal (../tool/node_modules/puppeteer/lib/cjs/puppeteer/common/ExecutionContext.js:221:19)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async ExecutionContext.evaluate (../tool/node_modules/puppeteer/lib/cjs/puppeteer/common/ExecutionContext.js:110:16)
    at async ../tool/download_figma_files.js:267:13
    
    
Проблемы начались сегодня ночью. По исходникам выглядит, как будто скрипт пытается вызвать dispatchEvent на отсутствующем html-элементе, но почему так - вопрос, ибо такой div в верстке на странице присутствует.

Если есть идеи, как этому можно помочь - буду очень благодарен!

**Comment by myasnikovdaniil** [comment]
Hello, I've had the same problem - you need to chande css selector in `download_figma_files.js` 268 line: button element instead of div. It will be like this:

`const mainMenu = document.querySelector('button[data-tooltip="main-menu"]');`

**Comment by azart** [comment]
> Hello, I've had the same problem - you need to chande css selector in `download_figma_files.js` 268 line: button element instead of div. It will be like this:
> 
> `const mainMenu = document.querySelector('button[data-tooltip="main-menu"]');`

В версии 0.0.5 описанное выше изменение нужно делать в файле figma_actions.js строка 189
