### ISSUE TITLE
Ошибка при скачивании некоторых файлов Cannot read property 'boundingBox' of null

### ISSUE THREAD

**Issue by nikitashekhov** [ritds/figma_backup#7]
При скачивании некоторых файлов получаем ошибку:
```
Starting to process new file (6/100), key: FILE_KEY
Opening an empty page
Opening the file page: https://www.figma.com/file/FILE_KEY/
Returned status: 200
Page title: FILE_TITLE
Directory to save the file: './_downloads/TEAM NAME/PROJECT NAME/'
Using menu to save the file
TypeError: Cannot read property 'boundingBox' of null
    at /home/USER/figma-backup/download_figma_files.js:245:69
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
```

При этом сам файл сохраняется, получится ли открыть, скоро проверим

**Comment by masta-man** [comment]
У меня такая ошибка была из-за авторизации через google. Создал тестовую учетку на прямую авторизацию (email/pass) и все заработало.
